### ISSUE TITLE
Add `feature` command

### ISSUE THREAD

**Issue by grabbou** [grabbou/este-cli#10]
To run `store` `actions` `state` `cursor` `page` @steida?

**Comment by steida** [comment]
Yes please :+1:

**Comment by grabbou** [comment]
Store actually runs `state` and `cursor` automatically to ensure the needed bits are `there` but we can create `feature` that will run `store`, `actions` and `page` (as `state` and `cursor` are store dependencies). Is that somehow clear? :D

**Comment by tajo** [comment]
:+1:

**Comment by steida** [comment]
:+1:

**Comment by grabbou** [comment]
Woooo!
