### ISSUE TITLE
Add translate generator

### ISSUE THREAD

**Issue by grabbou** [grabbou/este-cli#15]
```
este-cli g translate todos
```
Generates
```js
{
    "todos": {}
}
```
and

```
este-cli g translate todos name description
```
Generates
```js
{
   "todos": {
        "name": "todosName",
        "description": "todosDescription"
   }
}
```
Can be used to set up localised messages in e.g. `page` by default.

Syntax not super friendly, but this blueprint is designed to be mainly used by other ones (think of it as a private one)

**Comment by steida** [comment]
+1
